
#Lighting
[lights]
	#Show the supporter message. This is set to false after the first time.
	showSupporterMessage = false
	#If dynamic lights are enabled
	lightsEnabled = true
	#How bright the touch light is
	#Range: 0 ~ 15
	touchLightLuminance = 8
	#How long the touch light lasts in ticks
	#Range: 0 ~ 40
	touchLightDuration = 8
	#Light level an entity should emit when dynamic lights are on
	#Example entry: minecraft:blaze=15
	entity_lights = [
		"minecraft:blaze=10",
		"ars_nouveau:orbit=15",
		"ars_nouveau:linger=15",
		"ars_nouveau:spell_proj=15",
		"minecraft:magma_cube=8",
		"ars_nouveau:flying_item=10",
		"minecraft:spectral_arrow=8",
		"ars_nouveau:follow_proj=10"
		]
	#Light level an item should emit when held when dynamic lights are on
	#Example entry: minecraft:stick=15
	item_lights = [
		"minecraft:redstone_torch=10",
		"minecraft:soul_lantern=12",
		"minecraft:glow_ink_sac=10",
		"minecraft:verdant_froglight=15",
		"minecraft:blaze_rod=10",
		"minecraft:shroomlight=10",
		"minecraft:lantern=14",
		"minecraft:soul_torch=10",
		"minecraft:glow_berries=8",
		"minecraft:glowstone_dust=8",
		"minecraft:pearlescent_froglight=15",
		"minecraft:nether_star=14",
		"minecraft:glowstone=15",
		"minecraft:torch=14",
		"minecraft:campfire=14",
		"minecraft:soul_campfire=10",
		"minecraft:end_crystal=15",
		"minecraft:torchflower=8",
		"minecraft:ochre_froglight=15",
		"minecraft:lava_bucket=15",
		"minecraft:sea_lantern=15",
		"minecraft:magma_block=3",
		"minecraft:glow_lichen=4",
		"minecraft:magma_cream=6",
		"minecraft:experience_bottle=6",
		"quark:blaze_lantern=10",
		"quark:paper_lantern=12",
		"quark:paper_lantern_sakura=12",
		"quark:glowberry_sack=9",
		"quark:duskbound_lantern=15",
		"quark:soul_bead=6",
		"galosphere:amethyst_lamp=15",
		"galosphere:allurite_lamp=15",
		"galosphere:lumiere_lamp=15",
		"galosphere:glinted_amethyst_cluster=7",
		"galosphere:glinted_allurite_cluster=7",
		"galosphere:glinted_lumiere_cluster=7",
		"galosphere:chandelier=15",
		"galosphere:glow_ink_clumps=8",
		"etcetera:iridescent_lantern=12",
		"supplementaries:deepslate_lamp=15",
		"supplementaries:blackstone_lamp=15",
		"supplementaries:stone_lamp=15",
		"supplementaries:sconce_lever=14",
		"supplementaries:sconce_soul=10",
		"supplementaries:sconce=14",
		"suppsquared:brass_lantern=15",
		"suppsquared:crimson_lantern=15",
		"suppsquared:copper_lantern=15",
		"upgrade_aquatic:tooth_lantern=15",
		"upgrade_aquatic:glow_squid_bucket=10",
		"buzzier_bees:honey_lamp=15",
		"cataclysm:altar_of_fire=15",
		"cataclysm:burning_ashes=12",
		"cataclysm:dying_ember=4",
		"endlightened_end:helium_lantern=15",
		"endlightened_end:xenon_lantern=15",
		"arcaneessenceblock:essence_sack=10",
		"create:blaze_burner=10",
		"aquamirae:golden_moth_in_a_jar=15",
		"beachparty:palm_torch_item=15",
		"beachparty:palm_tall_torch=15",
		"betterarcheology:radiance_totem=15",
		"born_in_chaos_v1:lord_pumpkinheads_lamp=8",
		"born_in_chaos_v1:fel_lamp=8",
		"valhesia_structures:soul_brazier=10",
		"valhesia_structures:soul_brazier=14",
		"nethersdelight:magma_gelatin=6",
		"nethersdelight:propelpearl=8",
		"nethersdelight:propelplant_torch=14",
		"mcwbridges:bridge_torch=14",
		"mcwbridges:bridge_lantern=14",
		"meadow:oil_lantern=14",
		"mowziesmobs:glowing_jelly=10",
		"netherdepthsupgrade:glowdine=15",
		"netherdepthsupgrade:blazefih=10",
		"netherdepthsupgrade:glowdine_bucket=15",
		"netherdepthsupgrade:blazefish_bucket=15",
		"netherdepthsupgrade:soulsucker_bucket=14",
		"netherdepthsupgrade:fortress_grouper_bucket=14",
		"netherdepthsupgrade:eyeball_fish_bucket=14",
		"netherdepthsupgrade:magmacubefish_bucket=14",
		"netherdepthsupgrade:wither_bonefish_bucket=14",
		"netherdepthsupgrade:bonefish_bucket=14",
		"netherdepthsupgrade:searing_cod_bucket=14",
		"netherdepthsupgrade:obsidianfish_bucket=14",
		"netherdepthsupgrade:lava_pufferfish_bucket=14",
		"create_enchantment_industry:hyper_experience_bottle=10",
		"create_connected:fan_blasting_catalyst=15",
		"create_connected:fan_smoking_catalyst=14",
		"create_connected:fan_haunting_catalyst=10",
		"create_things_and_misc:neon_tube=15",
		"createbigcannons:molten_cast_iron_bucket=10",
		"createbigcannons:molten_bronze_bucket=10",
		"alexcaves:volcanic_core=10",
		"alexcaves:primal_magma=8",
		"alexcaves:carmine_froglight=15",
		"alexcaves:ambersol=15",
		"alexcaves:unrefined_waste=4",
		"alexcaves:uranium_rod=9",
		"alexcaves:block_of_uranium=4",
		"alexcaves:uranium=5",
		"alexcaves:uranium_shard=8",
		"alexcaves:radon_bottle=8",
		"alexcaves:radgill_bucket=7",
		"alexcaves:acid_bucket=7",
		"alexcaves:bioluminesscence=15",
		"alexcaves:bioluminescent_torch=15",
		"alexcaves:floater=15",
		]

#Overlay
[overlays]
	#X offset for the tooltip
	#Range: > -2147483648
	xTooltip = 20
	#Y offset for the tooltip
	#Range: > -2147483648
	yTooltip = 0
	#X offset for the Mana Bar
	#Range: > -2147483648
	xManaBar = 0
	#Y offset for the Mana Bar
	#Range: > -2147483648
	yManaBar = 0
	#If the Storage Lectern should show the recipe book icon
	showRecipeBook = true
	#Inform the player of Dynamic lights once.
	informLights = false

#Misc
[misc]
	#Use simplified renderer for Warp Portals
	no_end_portal_render = false
	#Disables the skyweave renderer. Disable if your sky is broken with shaders.
	disable_skyweave = false
	#Enables transparent/opaque rendering of elements in the book GUI. Disable if it leads to crash with Sodium derivatives
	gui_transparency = true
	#Disables translucent particles. Disable if your particles are invisible with shaders.
	opaque_particles = false

