
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				item = true
				chicken = true
				arrow = true
				salmon = true
				tnt_minecart = true
				zombie_villager = true
				cow = true
				pig = true
				horse = true
				skeleton = true
				bat = true
				zombie = true
				glow_squid = true
				cod = true
				witch = true
				drowned = true
				spider = true
				creeper = true
				lightning_bolt = true
				sheep = true
				experience_orb = true
				player = true
				enderman = true

			[light_sources.settings.entities.irons_spellbooks]
				necromancer = true

			[light_sources.settings.entities.sons_of_sins]
				betrayed_guzzler = true

			[light_sources.settings.entities.crittersandcompanions]
				koi_fish = true
				dumbo_octopus = true

			[light_sources.settings.entities.alexsmobs]
				flying_fish = true
				fly = true
				cockroach = true
				seal = true
				lobster = true
				emu = true
				catfish = true
				terrapin = true

			[light_sources.settings.entities.fishofthieves]
				splashtail = true
				wildsplash = true
				islehopper = true
				pondie = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.born_in_chaos_v1]
				decrepit_skeleton = true
				skeleton_demoman = true
				zombie_fisherman = true
				firelight_not_despawn = true
				decaying_zombie = true
				dark_vortex = true
				dread_hound = true
				baby_skeleton = true
				zombie_lumberjack = true
				corpse_fish = true
				swarmer = true
				zombie_bruiser = true
				spirit_guide = true
				restless_spirit = true
				bonescaller = true
				phantom_creeper = true
				bloody_gadfly = true
				zombie_clown = true
				door_knight = true
				corpse_fly = true
				maggot = true

			[light_sources.settings.entities.ars_nouveau]
				starbuncle = true
				gift_starby = true
				drygmy = true

			[light_sources.settings.entities.luminousworld]
				zebra = true
				deer = true
				bass_fish = true
				sunken_skeleton = true
				charaxes = true
				savannah_skeleton = true
				monarch = true
				swallowtail = true
				king_crab = true
				ringlet = true
				savannah_zombie = true
				trout_fish = true
				crab = true

			[light_sources.settings.entities.cataclysm]
				deepling = true
				deepling_brute = true
				deepling_angler = true

			[light_sources.settings.entities.quark]
				forgotten = true
				stoneling = true

			[light_sources.settings.entities.friendsandfoes]
				mauler = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.tumbleweed]
				tumbleweed = true

